import LampBoardCore
import Foundation

/// Carries across what the support directory held under the project's previous
/// name.
///
/// Two files matter and neither is recoverable from anywhere else.
///
/// `remotes` names the machines whose sessions join the column. It is read once
/// and imported into preferences, then never consulted again — so an app that
/// started under the new name imported an *empty* list, wrote it down, and closed
/// the door. The symptom is the worst kind: no error, no empty state, just a
/// remote machine that quietly stopped appearing, and a person who assumes the
/// tunnel broke.
///
/// `inbox` is the mailbox the chat window writes into. A message sitting in it
/// when the rename happened would never be delivered, and nothing would say so.
///
/// The scripts are deliberately **not** carried. They are regenerated by the
/// installer with the port and the harness of the moment, and copying a stale one
/// forward would resurrect a script that posts to the wrong place. The hook
/// registrations that pointed at them are removed by `HookInstaller.install`.
///
/// Nothing is deleted. The old directory stays where it is: this runs before the
/// user has had a chance to see whether anything went wrong, which is precisely
/// the moment not to remove their only copy.
enum SupportDirectoryMigration {

    /// Files worth carrying, and each one is here for a reason written above.
    private static let carried = ["remotes", "inbox"]

    static func run(fileManager: FileManager = .default) {
        // The end-to-end runs work in a fake home that has no history to inherit,
        // and importing into one would make a test depend on the machine it runs on.
        guard !AppConfig.isUsingHomeOverride else { return }

        let old = AppConfig.legacySupportDirectory
        let new = AppConfig.supportDirectory
        guard fileManager.fileExists(atPath: old.path) else { return }

        for name in carried {
            let source = old.appendingPathComponent(name)
            let destination = new.appendingPathComponent(name)
            guard fileManager.fileExists(atPath: source.path),
                  !fileManager.fileExists(atPath: destination.path)
            else { continue }

            try? fileManager.createDirectory(at: new, withIntermediateDirectories: true)
            do {
                try fileManager.copyItem(at: source, to: destination)
                Diagnostics.log("support: carried \(name) over from \(old.lastPathComponent)")
            } catch {
                // A file that will not copy is not a reason to refuse to start.
                // The consequence is a feature that looks switched off, which is
                // recoverable; refusing to launch is not.
                Diagnostics.log("support: could not carry \(name): \(error.localizedDescription)")
            }
        }
    }
}
